CREATE TABLE IF NOT EXISTS `empresas` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `UF` varchar(2) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `NOMEFANTASIA` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CNPJ` varchar(19) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fornecedores` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EMPRESA` int NOT NULL DEFAULT '0',
  `NOME` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0',
  `CPFCNPJ` varchar(19) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0',
  `DATACADASTRO` datetime DEFAULT NULL,
  `TELEFONE` json DEFAULT NULL,
  `RG` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DATANASCIMENTO` datetime DEFAULT NULL,
  `INSCMUNICIPAL` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `INSCESTADUAL` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `UF` varchar(2) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `EMPRESA` (`EMPRESA`),
  CONSTRAINT `EMPRESA` FOREIGN KEY (`EMPRESA`) REFERENCES `empresas` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;